### ISSUE TITLE
Add ARM/Apple M1 support

### ISSUE THREAD

**Issue by idontusenumbers** [skarpdev/hapi-aws-secrets-manager-emulator#32]
Any chance you could add ARM/Apple M1 support? Seems the upstream image has arm support already.

**Comment by pingvinen** [comment]
Hi @idontusenumbers 

I have made a PR, which upgrades the entire stack. As far as I can see, nodejs introduced Apple M1 support in version 16 and we were running on node 12 :)

Would you be willing to build the image locally using the branch and test it out? I do not have an Apple computer :)

**Comment by pingvinen** [comment]
Released as version `0.4.0` ... https://hub.docker.com/r/skarpdev/aws-secrets-manager-emulator/tags

**Comment by idontusenumbers** [comment]
I'm not sure what's involved with pushing an ARM version of the image, but it appears to be missing: https://hub.docker.com/r/skarpdev/aws-secrets-manager-emulator/tags

This might provide some guidance: https://www.docker.com/blog/multi-arch-build-and-images-the-simple-way/

**Comment by nover** [comment]
Thanks for reporting @idontusenumbers, we're tracking this via #34
