### ISSUE TITLE
Build and push multi-arch image

### ISSUE THREAD

**Issue by nover** [skarpdev/hapi-aws-secrets-manager-emulator#34]
Due to #32 we need to also build for multi arch using `docker buildx`.

Docs are here @pingvinen 
https://docs.docker.com/buildx/working-with-buildx/

**Comment by pingvinen** [comment]
I am working on it... Currently looking for someone with an Apple M1 machine to test it :) see #35

**Comment by pingvinen** [comment]
The image is now available with multi-platform support as of version [0.4.1](https://hub.docker.com/r/skarpdev/aws-secrets-manager-emulator/tags)

**Comment by idontusenumbers** [comment]
Nice! Thanks!

FYI the 0.4.0 had a `v` prefix, though the rest (including 0.4.1) do not; just wanted to make sure whatever you intended to happen was happening.

**Comment by pingvinen** [comment]
> FYI the 0.4.0 had a `v` prefix, though the rest (including 0.4.1) do not; just wanted to make sure whatever you intended to happen was happening.

Yeah, I noticed that too :) The releasing - and thus the tag name - is done manually and I work on other projects where the images are prefixed with `v`. I updated the "notes to self" in response to my error :) I noticed it too late, so I did not want to remove the tag that I had already pushed as someone might have started using it already.
